### PR TITLE
.NET Standard / Core Migration

### PR DESCRIPTION
**Pull request by pschnoop**
Since **System.Drawing** is now available on .NET Core I wanted to migrate your project.

I moved the assembly informations to the csproj files.
Plase have a look at the properties I removed from `netDxf.csproj`.
You might want to keep some of the values I removed.

I am open for suggestions :)

### CODE REVIEW

**Comment by hansmbakker** [comment]
@haplokuon could you please look into this?

Somebody else put a [netstandard version on nuget ](https://www.nuget.org/packages/netDxf.netstandard/); it would be good if it would be published from your repository!

**Comment by andreygursky** [comment]
This patch breaks building netDxf on Debian using Mono with
```
$ xbuild netDxf.sln
```

**Comment by hansmbakker** [comment]
@andreygursky what is the issue? Can you share the logs?

**Comment by andreygursky** [comment]
Sure.
<details>
  <summary>Build log:</summary>
  
```
/tmp/netDxf$ xbuild netDxf.sln

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 6.8.0.105
Copyright (C) 2005-2013 Various Mono authors

Build started 6/5/2020 12:24:17 PM.
__________________________________________________
/tmp/netDxf/netDxf.sln:  warning : /tmp/netDxf/netDxf/netDxf.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/tmp/netDxf/netDxf.sln:  warning : /tmp/netDxf/TestDxfDocument/TestDxfDocument.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
Project "/tmp/netDxf/netDxf.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Debug|Mixed Platforms".
	Target Build:
/tmp/netDxf/netDxf/netDxf.csproj: error : /tmp/netDxf/netDxf/netDxf.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/tmp/netDxf/TestDxfDocument/TestDxfDocument.csproj: error : /tmp/netDxf/TestDxfDocument/TestDxfDocument.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/tmp/netDxf/netDxf.sln".-- FAILED
Done building project "/tmp/netDxf/netDxf.sln".-- FAILED

Build FAILED.

Warnings:

/tmp/netDxf/netDxf.sln:  warning : /tmp/netDxf/netDxf/netDxf.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
/tmp/netDxf/netDxf.sln:  warning : /tmp/netDxf/TestDxfDocument/TestDxfDocument.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  

Errors:

/tmp/netDxf/netDxf.sln (default targets) ->
(Build target) ->

	/tmp/netDxf/netDxf/netDxf.csproj: error : /tmp/netDxf/netDxf/netDxf.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  
	/tmp/netDxf/TestDxfDocument/TestDxfDocument.csproj: error : /tmp/netDxf/TestDxfDocument/TestDxfDocument.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  

	 2 Warning(s)
	 2 Error(s)

Time Elapsed 00:00:00.3256040
```
</details>

**Comment by hansmbakker** [comment]
I'm not experienced with mono, but I believe that it should support at least NetStandard 2.0. NetStandard 2.0 uses a new csproj file format, while your `xbuild` program seems to expect an older version of the project format.

Is it possible you are using an outdated version of `xbuild`?

**Comment by andreygursky** [comment]
xbuild comes with the recent Mono 6.8.0.105+dfsg-3.

**Comment by hansmbakker** [comment]
I see this in your log:
> >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

So they recommend to use msbuild instead, which would support the modern project format.
Is there a need for you to use xbuild?

**Comment by andreygursky** [comment]
Yes, Debian does not provide msbuild. Still all packaged .NET projects can be successfully built.

**Comment by hansmbakker** [comment]
ok, I understand that it is inconvenient for your setup I'm not sure if a deprecated build tool should be a blocker for this PR?

When netDXF is packaged as netstandard2.0 dll in a Nuget package, I believe it can be consumed by all relatively modern setups.

People who use deprecated software can then keep using the older version of this library?

**Comment by andreygursky** [comment]
It is not necessary to replace the working project files, instead new one could be provided additionally. Then user can peek the best one.

**Comment by haplokuon** [comment]
Created a new branch net_5.0 that eventually will become the master.

**Pull request closed without merging**
